## NUMPY: FUNDAMENTAL PACKAGE FOR SCIENTIFIC COMPUTING IN PYTHON

In [6]:
import numpy as np

# 1D NUMPY ARRAY - VECTOR
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# 2D NUMPY ARRAY - MATRIX
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3D NUMPY ARRAY - TENSOR
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# dtype

print(np.array([1,2,3], dtype = float))
print(np.array([1,2,3], dtype = bool))

[1. 2. 3.]
[ True  True  True]


In [15]:
# np.arange

print(np.arange(1, 11))
print(np.arange(1,11,2))


[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [20]:
# with reshape

print(np.arange(1,11).reshape(2,5))
print(np.arange(1,13).reshape(3,4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
# np.ones and np.zeros

print(np.ones((3,4)))
print(np.zeros((2,6)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [27]:
# np.random

print(np.random.random((3,4)))

[[0.27824407 0.5044407  0.01440781 0.33918226]
 [0.61905101 0.67084691 0.36855314 0.04810827]
 [0.88793282 0.98616447 0.98360491 0.85708843]]


In [29]:
# np.linspace - provides euidistant in given range

# (a,b,c)
# a = lower range
# b = upper range
# c = number of item wants to generate

np.linspace(-10, 10, 10)



array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [30]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])