## ARRAY ATTRIBUTES

In [22]:
import numpy as np

In [23]:
a1 = np.arange(10)
a2 = np.arange(12, dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print("1D array \n",a1, "\n")
print("2D array \n",a2, "\n")
print("3D array \n",a3)


1D array 
 [0 1 2 3 4 5 6 7 8 9] 

2D array 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

3D array 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [24]:
# ndim

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [25]:
# shape

print(a1.shape)
print(a2.shape)
print(a3.shape)


(10,)
(3, 4)
(2, 2, 2)


In [26]:
# SIZE

print(a1.size)
print(a2.size)
print(a3.size)


10
12
8


In [27]:
# Itemsize

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [28]:
# DATATYPE

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# CHANGING DATATYPE

In [29]:
# astype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [30]:
a2.astype(np.int32)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# ARRAY OPERATIONS

In [31]:
b1 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)

print(b1)
print(b2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [32]:
# Scaler Operations

# Arithmetic Operator

b1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [33]:
# Relational Operator

b1 == 2

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
# Vector Operations

# Arithmetic Operator

# As their shape are equal
b1 + b2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [35]:
b1*b2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# ARRAY FUNCTIONS

In [36]:
c1 = np.random.random((3, 3))
c1 = np.round(c1*100)
c1

array([[62., 49., 20.],
       [30., 39., 78.],
       [44., 52., 52.]])

In [37]:
# max/min/sum/prod

print(c1)
print(np.max(c1))
print(np.min(c1))
print(np.sum(c1))
print(np.prod(c1))

[[62. 49. 20.]
 [30. 39. 78.]
 [44. 52. 52.]]
78.0
20.0
426.0
659716875417600.0


In [38]:
# 0 -> col and 1 -> row
np.prod(c1, axis = 0)

array([81840., 99372., 81120.])

In [39]:
# mean/ median / std/ var
np.mean(c1, axis = 1)

array([43.66666667, 49.        , 49.33333333])

In [40]:
# Trignometric functions

np.sin(c1)

array([[-0.7391807 , -0.95375265,  0.91294525],
       [-0.98803162,  0.96379539,  0.51397846],
       [ 0.01770193,  0.98662759,  0.98662759]])

In [48]:
# Dot Product

x = np.arange(12).reshape(3,4)
print(x)
y = np.arange(12, 24).reshape(4,3)
print(y)

np.dot(x,y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [49]:
# log and exponents
np.exp(x)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [54]:
# round/ floor/ ceil

print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[78.  8. 82.]
 [74.  8. 16.]]
[[62. 84. 55.]
 [28. 89. 53.]]
[[21. 44. 24.]
 [58.  9. 13.]]


# INDEXING and SLICING

In [55]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a1[0]

0

In [57]:
a1[-2]

8

In [58]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [59]:
# Variable[row_number, col_number]

a2[1,2]

6.0

In [60]:
# Variable[row_number, col_number]

a2[2,3]

11.0

In [61]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
# Variable[matrix, row_number, col_number]

# 5
a3[1, 0, 1]

5

In [63]:
# Variable[matrix, row_number, col_number]

# 5
a3[0, 1, 0]

2

In [64]:
# SLICING

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# 2 3 4 
print(a1[2:5])
print(a1[2:5:2])

[2 3 4]
[2 4]


In [67]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [69]:
# Only 1st Row
a2[0, :]

array([0., 1., 2., 3.])

In [70]:
# Only Column
a2[:, 2]

array([ 2.,  6., 10.])

In [71]:
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [72]:
#   alternate row_number , alternate col_number       
# Variable[::2, ::3 ]

a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [82]:
a2[::2, 1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [86]:
a2[1, ::3]

array([4., 7.])

In [90]:
# Variable[row_number_include:row_number_exclude, Col_number_include:Col_number_exclude]

a2[:2, 1:4]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [92]:
# Variable[row_number_include:row_number_exclude, Col_number_include:Col_number_exclude]

a2[:2, 1::2]

array([[1., 3.],
       [5., 7.]])

In [95]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
# Variable[matrix, row_number, col_number]
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [98]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
# a3[0, 1, :]
a3[0,1,:]

array([3, 4, 5])

In [102]:
a3[1, :, 1]

array([10, 13, 16])

In [104]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [110]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])