# NUMPY ARRAY AS PYTHON LISTS

In [8]:
import numpy as np

In [9]:
# Speed
# List
a = [i for i in range(100000000)]
b = [i for i in range(100000000, 200000000)]

c = []

import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

9.210613012313843


In [10]:
# Numpy
import numpy as np
a = np.arange(100000000)
b = np.arange(100000000, 200000000)

c = a + b
start = time.time()
print(time.time()-start)

0.0


In [11]:
# Memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [12]:
a = np.arange(10000000, dtype = np.int32)
sys.getsizeof(a)

40000112

## Advanced Indexing

In [21]:
# Normal Indexing and Slicing
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
a[1,2]

5

In [23]:
a[1:3, 1:3]

array([[4, 5],
       [7, 8]])

In [24]:
# Fancy Indexing
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
a[::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [26]:
# 1 row, 3 row, 4 row
a[[0, 2, 3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
b[[0, 2, 3, 5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [29]:
# For Column
b[:,[0,3]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19],
       [20, 23]])

## Boolean Indexing

In [30]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[56, 78, 55,  6],
       [10, 25, 66, 39],
       [75, 94, 11, 46],
       [93, 26, 21, 11],
       [11, 37, 31, 82],
       [50, 17,  7, 97]])

In [31]:
# Find all numbers greater than 50
print(a > 50)
a[a > 50]

[[ True  True  True False]
 [False False  True False]
 [ True  True False False]
 [ True False False False]
 [False False False  True]
 [False False False  True]]


array([56, 78, 55, 66, 75, 94, 93, 82, 97])

In [32]:
# Find even numbers
a[a%2 == 0]

array([56, 78,  6, 10, 66, 94, 46, 26, 82, 50])

In [36]:
# Find all numbers greater than 50 and even
a[(a>50) & (a%2 == 0)]

array([56, 78, 66, 94, 82])

In [38]:
# Find all numbers not divisible by 7
a[a % 7 == 0]

array([56, 21,  7])

## Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
<br>The smaller array is 'broadccast' across the larger array so that they have comaptible shapes.

# Same Shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)
print(a+b)

In [50]:
# Diff Shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


### Broadcasting Rules

#### 1. Make the two arrays have the same number of dimensions.
If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

#### 2. Make each dimension of the two arrays the same size.

If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
<br>If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [54]:
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [58]:
a = np.arange(12).reshape(3,4)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [59]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [60]:
a = np.array([1])
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [62]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 