# Numpy Tricks

In [3]:
import numpy as np

### 1. np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [4]:
a = np.random.randint(1,100,15)
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [5]:
np.sort(a)

array([ 2, 11, 28, 32, 42, 46, 51, 55, 68, 70, 71, 82, 91, 91, 97])

In [6]:
np.sort(a)[::-1]

array([97, 91, 91, 82, 71, 70, 68, 55, 51, 46, 42, 32, 28, 11,  2])

In [7]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[35, 95, 82, 26],
       [ 7, 27, 93, 72],
       [77, 86, 14, 85],
       [12, 89, 27, 13],
       [15, 81, 82, 20],
       [27, 11, 97, 19]])

In [8]:
np.sort(b)

array([[26, 35, 82, 95],
       [ 7, 27, 72, 93],
       [14, 77, 85, 86],
       [12, 13, 27, 89],
       [15, 20, 81, 82],
       [11, 19, 27, 97]])

### 2. np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [10]:
np.append(a, 70 )

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82, 70])

In [11]:
b

array([[35, 95, 82, 26],
       [ 7, 27, 93, 72],
       [77, 86, 14, 85],
       [12, 89, 27, 13],
       [15, 81, 82, 20],
       [27, 11, 97, 19]])

In [12]:
np.append(b, np.ones((b.shape[0],1)), axis = 1)    # axis = 0 is for columns

array([[35., 95., 82., 26.,  1.],
       [ 7., 27., 93., 72.,  1.],
       [77., 86., 14., 85.,  1.],
       [12., 89., 27., 13.,  1.],
       [15., 81., 82., 20.,  1.],
       [27., 11., 97., 19.,  1.]])

### 3. np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [13]:
c = np.arange(6).reshape(2,3)
d = np.arange(6, 12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d), axis=0)  # axis = 0 is for rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 4. np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
e = np.array([1,1,2,2,3,3,4,5,6,7,4,3])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

### 5. np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [18]:
a.shape

(15,)

In [19]:
np.expand_dims(a, axis=0)

array([[32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82]])

In [20]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [21]:
np.expand_dims(a, axis=1).shape

(15, 1)

### 6. np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [22]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [23]:
# Find all indices with value greater than 50
np.where(a>50)

(array([ 4,  6,  7,  8,  9, 11, 12, 13, 14], dtype=int64),)

In [24]:
# Replace all vaues  > 50 with 0
np.where(a>50, 0, a)

array([32, 42, 46,  2,  0, 11,  0,  0,  0,  0, 28,  0,  0,  0,  0])

In [25]:
np.where(a%2 == 0,0,a)

array([ 0,  0,  0,  0, 51, 11,  0, 91, 55, 91,  0, 71,  0, 97,  0])

### 7. np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [26]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [27]:
np.argmax(a)

13

In [28]:
b

array([[35, 95, 82, 26],
       [ 7, 27, 93, 72],
       [77, 86, 14, 85],
       [12, 89, 27, 13],
       [15, 81, 82, 20],
       [27, 11, 97, 19]])

In [29]:
np.argmax(b, axis=0)

array([2, 0, 5, 2], dtype=int64)

In [30]:
np.argmax(b, axis=1)

array([1, 2, 1, 1, 2, 2], dtype=int64)

In [31]:
np.argmin(a)

3

### 8. np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [32]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [33]:
np.cumsum(a)

array([ 32,  74, 120, 122, 173, 184, 252, 343, 398, 489, 517, 588, 658,
       755, 837])

In [34]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [35]:
np.cumprod(a)

array([         32,        1344,       61824,      123648,     6306048,
          69366528,   421956608,  -256654336, -1231086592,  -359730176,
       -1482510336,  2115948544,  2087510016,   625008640,  -288899072])

### 9. np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [36]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [37]:
np.percentile(a,100)

97.0

In [38]:
np.percentile(a,0)

2.0

In [39]:
np.percentile(a,50)

55.0

### 10. np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [40]:
a 

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [42]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 1, 1, 2, 2, 1, 2, 1, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### 11. np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [45]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [47]:
b = np.random.randint(1,100,15)
b

array([73, 88, 43, 65,  2, 62, 46, 55, 40, 17,  8, 53, 89, 29, 82])

In [50]:
np.corrcoef(a,b)

array([[ 1.        , -0.12399169],
       [-0.12399169,  1.        ]])

In [55]:
salary = np.array([20000,40000,25000,35000,60000])
exp = np.array([1,3,2,2,4])

np.corrcoef(salary, exp)

array([[1.        , 0.95746162],
       [0.95746162, 1.        ]])

### 12. np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [56]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [59]:
items = [10,20,30,40,50,60,70,80,90]
a[np.isin(a, items)]

array([70])

### 13. np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [60]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [61]:
np.sort(a)

array([ 2, 11, 28, 32, 42, 46, 51, 55, 68, 70, 71, 82, 91, 91, 97])

In [63]:
np.flip(np.sort(a))

array([97, 91, 91, 82, 71, 70, 68, 55, 51, 46, 42, 32, 28, 11,  2])

### 14. np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [64]:
a

array([32, 42, 46,  2, 51, 11, 68, 91, 55, 91, 28, 71, 70, 97, 82])

In [65]:
# np.put(variable, index, valur to replace)
np.put(a,[0,1],[100,234])

In [66]:
a

array([100, 234,  46,   2,  51,  11,  68,  91,  55,  91,  28,  71,  70,
        97,  82])

### 15. np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [67]:
a

array([100, 234,  46,   2,  51,  11,  68,  91,  55,  91,  28,  71,  70,
        97,  82])

In [69]:
np.delete(a,[5])

array([100, 234,  46,   2,  51,  68,  91,  55,  91,  28,  71,  70,  97,
        82])

### 16. Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [73]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [74]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
np.intersect1d(m,n)

array([3, 4, 5])

In [77]:
np.setdiff1d(m,n)

array([1, 2])

In [78]:
np.setdiff1d(n,m)

array([6, 7])

In [79]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [81]:
np.in1d(m,3)

array([False, False,  True, False, False])

### 17. np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [82]:
a

array([100, 234,  46,   2,  51,  11,  68,  91,  55,  91,  28,  71,  70,
        97,  82])

In [84]:
np.clip(a, a_max=75, a_min=25)

array([75, 75, 46, 25, 51, 25, 68, 75, 55, 75, 28, 71, 70, 75, 75])

In [87]:
# np.swapaxes

In [ ]:
# 