## Creating numpy/ n-d arrays

In [3]:
import numpy as np

#### Using np.array()// 1D and 2D

In [5]:
arr1 = np.array([1,2,3,4,5]) #Vector
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [9]:
arr2 = np.array([[1,2,3],[4,5,6]]) #Matrix
arr2

array([[1, 2, 3],
       [4, 5, 6]])

#### Using np.zeros/ones/empty/random()

In [11]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Using np.identity()

In [20]:
arr5 = np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Using np.arange()

In [32]:
arr6 = np.arange(1,20)
arr7 = np.arange(1,20,2)
print(arr6)
print(arr7)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


#### Using np.linspace()

In [34]:
arr8 = np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

#### Using np.Copy()

In [36]:
arr9 = arr7.copy()
arr9

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])