## Numpy Array Properties and Attributes

In [3]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5]) #Vector
arr1

array([1, 2, 3, 4, 5])

#### Using Shape/ nDIM

In [15]:
print(arr1.shape) #Shape of matrix
print(arr1.ndim)  # dimension

(5,)
1


In [9]:
arr2 = np.array([[1,2,3],[4,5,6]]) #Matrix
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(arr2.shape)
print(arr2.ndim)

(2, 3)

In [17]:
arr3 = np.array([[[1,2],[3,4]], [[4,5],[6,7]]]) #Array is function in python that's y we use () 
arr3

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [19]:
print(arr3.shape)
print(arr3.ndim)

(2, 2, 2)
3


#### Using Size

In [21]:
arr1.size

5

In [23]:
arr3.size

8

#### Using Itemsize

In [29]:
print(arr1.itemsize)
print(arr3.itemsize)

4
4


#### Using Dtype

In [33]:
 arr3.dtype

dtype('int32')

#### Using astype()

In [37]:
arr2.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.]])