## Numpy 

##### 1. Indexing
##### 2. Slicing
##### 3. Iteration


In [16]:
import numpy as np

In [17]:
arr1 = np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
arr2 = np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
arr2[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
arr2[-1]

array([20, 21, 22, 23])

In [23]:
 arr2[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [29]:
arr2[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [31]:
for i in arr2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [33]:
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Numpy Operations

In [34]:
arr3 = np.array([1,2,3,4,5,6])
arr4 = np.array([4,5,6,7,8,9])


In [35]:
arr4 - arr3

array([3, 3, 3, 3, 3, 3])

In [36]:
arr4 * arr3

array([ 4, 10, 18, 28, 40, 54])

In [38]:
arr4 > 5

array([False, False,  True,  True,  True,  True])

In [42]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [41]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [44]:
arr4.max()

11

In [45]:
arr3.min()

0

In [47]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
arr4.min(axis=0)

array([6, 7])

In [48]:
arr4.sum()

51

In [49]:
#Sum col
arr4.sum(axis = 0)

array([24, 27])

In [50]:
arr4.mean()

8.5

In [51]:
arr4.std()

1.707825127659933

In [52]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [53]:
np.median(arr4)

8.5

In [54]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])