# Numpy Reshaping

In [ ]:
#1. Ravel
#2. Reshape
#3. Transpose
#4. Stacking
#5. Splitting

In [1]:
import numpy as np

In [6]:
arr1 = np.array([[5,6],[7,8],[9,10]])

In [7]:
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
arr1.ndim

2

In [9]:
arr1.ravel()

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr1.transpose()

array([[ 5,  7,  9],
       [ 6,  8, 10]])

In [15]:
arr2 = np.arange(12,18).reshape(2,3)
arr3 = np.arange(34,40).reshape(2,3)

In [17]:
np.hstack((arr2, arr3))

array([[12, 13, 14, 34, 35, 36],
       [15, 16, 17, 37, 38, 39]])

In [18]:
np.vstack((arr2, arr3))

array([[12, 13, 14],
       [15, 16, 17],
       [34, 35, 36],
       [37, 38, 39]])

In [22]:
np.hsplit(arr3, 3)
np.vsplit(arr2,2)

[array([[12, 13, 14]]), array([[15, 16, 17]])]

### Fancy Indexing in Numpy

In [23]:
arr4 = np.arange(24).reshape(6,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
arr4[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

### Indexing with Boolean Arrays

In [28]:
arr5 = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr5

array([[28, 62, 86, 45, 47],
       [32, 36, 17, 93, 36],
       [85, 68, 72, 21, 79],
       [94, 71, 11, 70, 28]])

In [29]:
arr5[3]

array([94, 71, 11, 70, 28])

In [31]:
arr5>50

array([[False,  True,  True, False, False],
       [False, False, False,  True, False],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True, False]])

In [32]:
# Indexing using boolean array
arr5[arr5>50]

array([62, 86, 93, 85, 68, 72, 79, 94, 71, 70])

In [35]:
arr5[(arr5>50) & (arr5%2 != 0)]

array([93, 85, 79, 71])

In [36]:
arr5[(arr5>50) & (arr5%2 != 0)] = 0

In [37]:
arr5

array([[28, 62, 86, 45, 47],
       [32, 36, 17,  0, 36],
       [ 0, 68, 72, 21,  0],
       [94,  0, 11, 70, 28]])