In [1]:
import numpy as np

In [6]:
np.random.random()

0.7203244934421581

In [7]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [10]:
np.random.uniform(3, 10)

3.000800623721414

In [14]:
np.random.uniform(1,100,10).reshape(2, 5)

array([[69.53993895, 87.76252608, 89.56605969,  9.41937693,  4.86642354],
       [17.81321154, 87.93610784, 10.73633655, 42.68965488, 95.83106348]])

In [18]:
np.random.randint(1, 10, 5)

array([8, 8, 9, 7, 4])

In [20]:
np.random.randint(1, 10, 15).reshape(3,5)

array([[7, 9, 1, 3, 8],
       [8, 8, 4, 1, 9],
       [8, 8, 2, 2, 4]])

In [23]:
a = np.random.randint(1, 10, 6)
a

array([1, 9, 7, 5, 6, 7])

In [24]:
np.max(a)

9

In [25]:
np.min(a)

1

In [27]:
a[np.argmax(a)]

9

In [28]:
a[np.argmin(a)]

1

In [30]:
np.argmin(a)

0

In [34]:
b = np.random.randint(1, 10, 5)
b

array([9, 5, 1, 2, 9])

In [36]:
b[b%2==1] = -1
b

array([-1, -1, -1,  2, -1])

In [37]:
c = np.random.randint(1, 30, 5)
c

array([19, 20,  2,  3, 13])

In [38]:
np.where(c%2==1, -1, c)

array([-1, 20,  2, -1, -1])

In [39]:
c

array([19, 20,  2,  3, 13])

In [40]:
out = np.where(a%2==1, -1, a)
out

array([-1,  6,  8, -1, -1])

In [41]:
d = np.random.randint(1, 50, 10)
d

array([29, 40, 35, 11, 33, 42, 19, 23,  7,  3])

In [43]:
np.sort(d)

array([ 3,  7, 11, 19, 23, 29, 33, 35, 40, 42])

In [44]:
np.percentile(d,25)

13.0

In [48]:
np.percentile(d,98)

41.64